### ISSUE TITLE
Implement Aggregations on Geo Shape

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/geospatial#104]
### Description
This issue tracks the different tasks that are required to be done to implement and launch Aggregations on GeoShape Field. We will be adding 4 different Aggregations on the Geo Shape data type of Open Search.

1. Geo Bounds Aggregation
2. Geo Centroid Aggregation
3. Geo Hash Aggregation
4. Geo Tile Aggregation 

### Tasks

- [X] Uber level RFC for Geo Shape Aggregations
- [X] Low level implementation details for Geo Shape Aggregation
- [x] Enable Shape Doc value for the GeoShape Field (https://github.com/opensearch-project/OpenSearch/issues/4049)
- [x] Implement and Launch Geo Bounds Aggregation (https://github.com/opensearch-project/OpenSearch/issues/3980)
- [ ] Implement and Launch Geo Centroid Aggregation
- [x] Implement and Launch Geo Hash Aggregation (https://github.com/opensearch-project/OpenSearch/issues/4071)
- [x] Implement and Launch Geo Tile Aggregation (https://github.com/opensearch-project/OpenSearch/issues/4072)

### Useful Links
1. Uber level RFC: #84 
2. Low Level Implementation Details: #92 
3. Geo Bounds RFC: #93 
4. Doc Values on Geo Shape: https://github.com/opensearch-project/OpenSearch/issues/4049

**Comment by heemin32** [comment]
All feature is delivered except geo centroid aggregation. For geo centroid aggregation, will close it for now until there is explicit request from a community.
