### ISSUE TITLE
Merge Geo_Points and Geo_Shape CoreValue Source Type to 1 single Core Value Source Type Geo

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/geospatial#124]
### Description
As part of implementing aggregation on Geo_Shape, we went ahead and enabled the doc values for the GeoShape and CoreValue Source Type for the Geoshape as GEO_SHAPE. During the [PR](https://github.com/opensearch-project/OpenSearch/pull/3992#discussion_r931281225) it was suggested if we can combine the [GEOPOINT](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/support/CoreValuesSourceType.java#L157) and GEO_SHAPE(code will be added with GeoShape Aggregations Launch) CoreValueSource Type to GEO, rather than having 2 different SourceTypes.

### Tasks

- [ ] Identify if it is feasible to combine the 2 value source type to 1 CoreValueSource Type.
- [ ] Build the Low Level Design for the same.
- [ ] Implement the changes to combine
